# Generated by Django 4.2.4 on 2023-09-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.EmailField(max_length=50, verbose_name='Enter email')),
                ('phone', models.CharField(default='', max_length=12, verbose_name='Phone number')),
                ('desc', models.CharField(default='', max_length=120, verbose_name='description')),
            ],
        ),
    ]
