# Generated by Django 4.2.4 on 2023-09-10 08:13

from django.db import migrations, models
import reg_login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=10, verbose_name='FName')),
                ('lname', models.CharField(max_length=10, verbose_name='LName')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25, validators=[reg_login.models.mail_validator], verbose_name='password')),
            ],
        ),
    ]
