# Generated by Django 4.2.4 on 2023-09-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=20, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fname',
            field=models.CharField(max_length=20, verbose_name='FName'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lname',
            field=models.CharField(max_length=20, verbose_name='LName'),
        ),
    ]
