# Generated by Django 4.2.4 on 2023-09-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_login', '0002_alter_registration_email_alter_registration_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='fname',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='lname',
            new_name='Lastname',
        ),
    ]
