# Generated by Django 4.2.4 on 2023-09-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_login', '0003_rename_fname_registration_firstname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registration',
            new_name='register',
        ),
    ]
